CREATE TABLE financial_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_id BIGINT NOT NULL,
    title VARCHAR(255),
    target_amount NUMERIC(19,2),
    current_amount NUMERIC(19,2) DEFAULT 0,
    deadline DATE,
    FOREIGN KEY (budget_id) REFERENCES budgets(id)
);